-- ============================================================================
-- 0038 — The real Oso Lounge and Boom Boom Room menus.
--
-- catalog_items held five placeholder drinks with invented prices. This loads
-- the venues' actual printed menus, transcribed from their own PDFs: Oso's food
-- and drinks lists (~230 items) and the Boom Boom Room price list (~65 items),
-- each item filed under the section it appears in and ordered as printed.
--
-- The four drink placeholders are DEACTIVATED rather than deleted: three of
-- them are referenced by existing collect_order_items, and deleting a catalog
-- item would either break that foreign key or rewrite order history. Setting
-- is_active = false takes them out of the shop while leaving past orders
-- readable. The merch placeholder (Kamadeva Prive Cap) stays active under a
-- Merchandise section, since it is not a menu item and nothing replaces it.
--
-- Prices are in kobo, exactly as printed on the menus (Oso's are inclusive of
-- the listed figure; the POS applies VAT and consumption tax separately).
-- ============================================================================

-- Venues are resolved by SLUG, and the whole seed is guarded.
--
-- This originally carried the production UUIDs for Oso Lounge and the Boom Boom
-- Room, and the production id of the founder who seeded the first catalogue.
-- Those values exist in exactly one database. 0010_seed_venues.sql inserts
-- venues without fixed ids, so anywhere else — CI, a rebuild from migrations,
-- disaster recovery — they resolve to nothing and this failed on
-- catalog_items_venue_id_fkey. Slugs are stable across every environment.
--
-- created_by is NOT NULL against staff_profiles, and no migration seeds a staff
-- row, so a database that has never had a staff account created through the app
-- genuinely cannot hold this data. Rather than invent a fake staff row, the
-- seed skips: these are the venues' real printed menus, and they mean nothing
-- in a database with no venues and no staff to attribute them to.
do $seed$
declare
  v_staff uuid := (select id from staff_profiles order by created_at limit 1);
begin
  if v_staff is null
     or not exists (select 1 from venues where slug in ('oso', 'bbr')) then
    raise notice 'no venues/staff seeded here — skipping the venue menu seed';
    return;
  end if;

  -- Retire the placeholder drinks; keep the rows so orders that used them resolve.
  update catalog_items set is_active = false
   where venue_id in (select id from venues where slug in ('oso', 'bbr'))
     and name in ('Hennessy XO','Moet Imperial','Moët Impérial',
                  'Casamigos Blanco','Dom Perignon Vintage','Dom Pérignon Vintage');

  -- Keep the one non-menu item, filed so it does not float loose in the shop.
  update catalog_items set category = 'Merchandise', sort_order = 0
   where name = 'Kamadeva Privé Cap';

  insert into catalog_items (venue_id, name, description, price_kobo, category, sort_order, created_by)
  select ven.id, v.name, v.description, v.price_kobo, v.category, v.sort_order, v_staff
  from (values
  ('oso', 'Chicken Wings', 'Lemon pepper, mango chili or honey BBQ.', 1850000, 'Starters & Appetizers', 0),
  ('oso', 'Beef and Goat Meat Sliders', 'Goat meat patties and BBQ beef filling on three toasted mini buns.', 1950000, 'Starters & Appetizers', 1),
  ('oso', 'Smoked Chicken Quesadilla', 'Toasted quesadilla with smoked chicken and caramelised onions, guacamole or salsa.', 2050000, 'Starters & Appetizers', 2),
  ('oso', 'Cheesy Chicken Lollipops', 'Breaded and fried, made of ground chicken, potatoes, cheese and spices.', 2200000, 'Starters & Appetizers', 3),
  ('oso', 'Shrimp Popcorn', 'Bite-size shrimps in a spice mix, battered and deep-fried.', 1950000, 'Starters & Appetizers', 4),
  ('oso', 'Shrimp Spring Rolls', 'Four rolls with seasoned shrimp and herbs, served with a dip.', 1850000, 'Starters & Appetizers', 5),
  ('oso', 'Tacos', 'Soft or hard shell with beef, chicken or shrimp, veggies and melted cheese.', 2250000, 'Starters & Appetizers', 6),
  ('oso', 'Garlic Parm Chicken Skewers', 'Marinated chicken cubes grilled on a stick, tossed in garlic oil and parmesan.', 2450000, 'Starters & Appetizers', 7),
  ('oso', 'Spicy Peppersoup', 'The Naija classic topped with yam or Irish potatoes. Catfish, chicken, goat meat or beef.', 1950000, 'Soups', 0),
  ('oso', 'Soup of the Day', 'Ask our waiting staff for the soup of the day.', 1650000, 'Soups', 1),
  ('oso', 'Chicken Caesar Salad', 'Crispy lettuce, grilled chicken, parmesan and croutons with creamy caesar dressing.', 2250000, 'Salads', 0),
  ('oso', 'Seafood Salad', 'Shrimp and tuna with celery, red onions and fresh dill, in oyster sauce, mayo and lime.', 2450000, 'Salads', 1),
  ('oso', 'Oso''s Waldorf', 'Lettuce, kale, green grapes, boiled eggs, celery and roasted nuts in greek yoghurt dressing.', 2050000, 'Salads', 2),
  ('oso', 'Chicken Burrito Bowl', 'Lime-cilantro rice, kidney beans, red onions, tomatoes, lettuce, corn, sour cream and grilled chicken.', 2850000, 'Protein Bowls', 0),
  ('oso', 'Hoisin Rice Bowl', 'Chicken or beef strips, broccoli, brown rice, orange and cashews with sriracha or chili oil.', 2950000, 'Protein Bowls', 1),
  ('oso', 'Salmon Poke Bowl', 'White rice, glazed salmon, cucumber, peas, avocado, cherry tomatoes, mayo and chili flakes.', 3750000, 'Protein Bowls', 2),
  ('oso', 'Beef Egg Noodle Bowl', 'Egg noodles, beef and stir-fried vegetables, topped with boiled eggs.', 2250000, 'Protein Bowls', 3),
  ('oso', 'Chicken Bacon Club', 'Grilled chicken breast and beef bacon with rocket and egg on toasted bread.', 2050000, 'Burgers & Sandwiches', 0),
  ('oso', 'Oso Burger Royale', 'Double beef patty with cheese, beef bacon, tomato, pickles, onions and signature sauce, with fries. Single patty 13,500.', 2450000, 'Burgers & Sandwiches', 1),
  ('oso', 'Crispy Chicken Sandwich', 'Fried chicken on a toasted brioche bun with pickles, honey-mustard coleslaw and tomato.', 2350000, 'Burgers & Sandwiches', 2),
  ('oso', 'Egg and Bacon Bagel', 'The NY classic — poached egg and crispy beef bacon on a freshly baked bagel.', 2550000, 'Burgers & Sandwiches', 3),
  ('oso', 'Breakfast Burrito', 'Scrambled eggs, hash browns, smoked sausage and cheese.', 2350000, 'Burgers & Sandwiches', 4),
  ('oso', 'Stuffed Pita (Arayes)', 'Pita stuffed with spiced ground meat, grilled crisp, with yoghurt and herb sauce.', 2350000, 'Burgers & Sandwiches', 5),
  ('oso', 'Picante de Gallina', 'Hot chicken basket in a creamy sauce.', 2300000, 'Tapas', 0),
  ('oso', 'Rabo de Toro', 'Oxtail braised to tenderness in tomato and red wine stew.', 2850000, 'Tapas', 1),
  ('oso', 'Alitas de Pavo Picantes', 'Spanish-style spicy turkey wings.', 2350000, 'Tapas', 2),
  ('oso', 'Egg Fried Rice', 'Basmati rice, eggs, garlic and soy sauce with spring onion. Chicken, beef or sausage +4,500.', 1650000, 'Rice & Pasta', 0),
  ('oso', 'Spicy Meatballs Spaghetti', 'Spaghetti in tomato and basil sauce with spicy meatballs.', 2450000, 'Rice & Pasta', 1),
  ('oso', 'Pasta Carbonara', 'Penne, spaghetti or macaroni in a creamy egg sauce, topped with crispy beef bacon.', 2500000, 'Rice & Pasta', 2),
  ('oso', 'Chicken Alfredo Pasta', 'Your choice of pasta in herb cream and cheese sauce with golden chicken strips.', 2550000, 'Rice & Pasta', 3),
  ('oso', 'Creamy Shrimp Fettuccine', 'Fresh shrimps in a creamy Chardonnay sauce with fettuccine.', 2750000, 'Rice & Pasta', 4),
  ('oso', 'Spicy Fish Linguini', 'Linguini in tomato sauce and spiced chilli oil with boneless croaker cubes.', 2750000, 'Rice & Pasta', 5),
  ('oso', 'Grilled Salmon Filet', 'Grilled salmon with maple Dijon roasted carrots, vegetables and mashed potatoes.', 6250000, 'Seafood', 0),
  ('oso', 'Shrimp Boil Foil Pack', 'Shrimps with potatoes, corn and smoked sausage in brown butter sauce and lemon.', 4450000, 'Seafood', 1),
  ('oso', 'Grilled Jumbo Prawns', 'Four large prawns grilled in herbs and spices, served with fries.', 4950000, 'Seafood', 2),
  ('oso', 'Sea Bass Filet', 'Grilled or fried with herbs, lemon butter sauce and white rice.', 3950000, 'Seafood', 3),
  ('oso', 'Honey Glazed BBQ Baby Chicken', 'Whole baby chicken grilled BBQ style, served with fries.', 4250000, 'Meats & Chicken', 0),
  ('oso', 'Grilled Lamb Chops', 'Marinated in herbs and spices, grilled tender, with a side of your choice.', 6550000, 'Meats & Chicken', 1),
  ('oso', 'Sweet and Savory Pork Belly', 'Cooked in ginger, spices and herbs with a sweet kick, with veggies and fries.', 4450000, 'Meats & Chicken', 2),
  ('oso', 'Spinach and Artichoke Stuffed Chicken Breasts', 'Oven-baked breaded chicken breast with creamy spinach and artichoke filling.', 4150000, 'Meats & Chicken', 3),
  ('oso', 'Beef Steak', 'T-bone or ribeye 250g, grilled to your liking with Penja pepper and Dijon, with fries.', 6200000, 'Meats & Chicken', 4),
  ('oso', 'Seafood Platter', 'Calamari, shrimps, fish fingers, sautéed crab, breaded octopus and white fish filet. Serves 4.', 9450000, 'Platters', 0),
  ('oso', 'Meat Platter', 'Spicy goat meat, BBQ ribs, bacon-wrapped wings, beef soya, mini chicken wrap and beef skewers, with fries and dips.', 8500000, 'Platters', 1),
  ('oso', 'Steamed Basmati Rice', null, 750000, 'Sides', 0),
  ('oso', 'Steamed / Sautéed Vegetables', null, 750000, 'Sides', 1),
  ('oso', 'Fried Ripe Plantain', null, 800000, 'Sides', 2),
  ('oso', 'Oso''s Smoky Jollof', null, 950000, 'Sides', 3),
  ('oso', 'Crispy French Fries', 'Ask for curly, crinkle cut or waffle shape.', 1050000, 'Sides', 4),
  ('oso', 'Mashed Potatoes', null, 1150000, 'Sides', 5),
  ('oso', 'Rice with Kidney Beans and Thyme', null, 1200000, 'Sides', 6),
  ('oso', 'French Crêpes', 'Duo of crêpes with strawberry and syrup, banana and chocolate, or orange jam.', 1350000, 'Dessert', 0),
  ('oso', 'Churros & Chocolate Dip', 'Sugar and cinnamon churros with a cocoa-rich chocolate dip.', 1450000, 'Dessert', 1),
  ('oso', 'Sweet Puff Puff', 'Naija-style fried dough balls. Toppings: sugar, honey or white chocolate.', 1450000, 'Dessert', 2),
  ('oso', 'Ice Cream Browny', 'Rich browny topped with a scoop of vanilla ice cream.', 1480000, 'Dessert', 3),
  ('oso', 'Kir Imperial', 'Raspberry liqueur with Prosecco/bubbly sparkling wine.', 1950000, 'Champagne Cocktails', 0),
  ('oso', 'Kir Royal', 'A classic combination of crème de cassis and champagne.', 2250000, 'Champagne Cocktails', 1),
  ('oso', 'Peach Bellini', 'The classic combination of peach liqueur and champagne.', 2050000, 'Champagne Cocktails', 2),
  ('oso', 'Mimosa', 'Cointreau, fresh orange juice and champagne.', 2050000, 'Champagne Cocktails', 3),
  ('oso', 'Mint Grapefruit Mimosa', 'Simple syrup, grapefruit and fresh mint, topped with cold Prosecco.', 2050000, 'Champagne Cocktails', 4),
  ('oso', 'Mint Julep', 'Bourbon, sugar, water, crushed ice and fresh mint.', 1950000, 'New Age Cocktails', 0),
  ('oso', 'Gin Basil Smash', 'Gin, lemon juice, simple syrup and fresh basil, shaken and served on ice.', 1950000, 'New Age Cocktails', 1),
  ('oso', 'Negroni with a Twist', 'Sweet vermouth, Campari, lemon, orange, gin and rosemary syrup, topped with smoked rosemary.', 1950000, 'New Age Cocktails', 2),
  ('oso', 'Beergarita', 'Your flavour of frozen margarita topped with cold lager, in a giant glass.', 2250000, 'New Age Cocktails', 3),
  ('oso', 'Classic Mojito', 'White rum, fresh mint, lime and soda. Ask for strawberry or mango.', 1950000, 'Classic Cocktails', 0),
  ('oso', 'Long Island', 'Oso''s fan favourite — vodka, gin, tequila and Cointreau with syrup, lemon and a dash of coke.', 1950000, 'Classic Cocktails', 1),
  ('oso', 'Gin Tonic', 'The classic gin and tonic on ice with lemon.', 1950000, 'Classic Cocktails', 2),
  ('oso', 'Moscow Mule', 'Vodka, fresh lime and ginger beer. Ask for the Jamaican mule with dark rum.', 1950000, 'Classic Cocktails', 3),
  ('oso', 'The White Lady', 'Gin, Cointreau and fresh lime juice.', 1950000, 'Classic Cocktails', 4),
  ('oso', 'Cosmopolitan', 'Cranberry, Cointreau and fresh lime combined with vodka.', 1950000, 'Classic Cocktails', 5),
  ('oso', 'Whisky Sour', 'Whiskey shaken with fresh lemon juice and sugar syrup. Ask for egg white.', 1950000, 'Classic Cocktails', 6),
  ('oso', 'Old Fashioned', 'Fresh orange muddled with sweet and sour mix, topped with whiskey over crushed ice.', 1950000, 'Classic Cocktails', 7),
  ('oso', 'Aperol Spritz', 'Aperol, Prosecco and soda water, garnished with an orange slice.', 1950000, 'Classic Cocktails', 8),
  ('oso', 'Aperol Gin Twirl', 'Aperol, gin, simple syrup, lime juice and soda water.', 1950000, 'Classic Cocktails', 9),
  ('oso', 'Frozen Margarita', 'The classic margarita with tequila, Cointreau and lime. Ask for strawberry or passion fruit.', 1950000, 'Classic Cocktails', 10),
  ('oso', 'Frozen Daiquiri', 'Rum, simple syrup, lime and the flavour of your choice, over shaved ice.', 1950000, 'Classic Cocktails', 11),
  ('oso', 'Piña Colada', 'Malibu and light rum shaken with pineapple, coconut milk, coconut syrup, milk and cream.', 1950000, 'Classic Cocktails', 12),
  ('oso', 'Obaje''s Honey Pot', 'Honey, tequila, spiced rum, fresh lemon and ginger beer — a team favourite.', 2080000, 'Oso''s Exclusive Creations', 0),
  ('oso', 'Coconut Aperol Margarita', 'Tequila, coconut milk, syrup, Cointreau, lime juice and Aperol.', 2080000, 'Oso''s Exclusive Creations', 1),
  ('oso', 'Missionary''s Downfall', 'Pineapple, mint, white rum, peach liqueur, lime, honey syrup and peach bitters.', 2080000, 'Oso''s Exclusive Creations', 2),
  ('oso', 'Clear ''n'' Stormy', 'White rum, lime, syrup, ginger beer and Angostura bitters.', 2080000, 'Oso''s Exclusive Creations', 3),
  ('oso', 'Whisky Ginger', 'Whisky, fresh ginger, simple syrup, lime juice and soda.', 2080000, 'Oso''s Exclusive Creations', 4),
  ('oso', 'Summer in Scotland', 'Smoky scotch, Cointreau, popcorn syrup and orange extract — sweet and smoky.', 2080000, 'Oso''s Exclusive Creations', 5),
  ('oso', 'Run This Town', 'Rye, vermouth, espresso, chocolate bitters and a dash of coke.', 2080000, 'Oso''s Exclusive Creations', 6),
  ('oso', 'Indomitable Spirit', 'Tequila, Cointreau, red wine and lime juice.', 2080000, 'Oso''s Exclusive Creations', 7),
  ('oso', 'Oso''s Grog', 'Pineapple, cranberry, coconut nectar, lime, double cream float and cinnamon dust.', 1350000, 'Mocktails', 0),
  ('oso', 'Oso''s Quine', 'Tonic water, soda water and bitters.', 1350000, 'Mocktails', 1),
  ('oso', 'Oso''s Passion Delights', 'Passion fruit purée, orange juice, lemon and simple syrup.', 1350000, 'Mocktails', 2),
  ('oso', 'Orange Pineapple Punch', 'Lime, pineapple, orange, sprite and a touch of ginger.', 1350000, 'Mocktails', 3),
  ('oso', 'Chapman', 'The Nigerian classic — sprite and Fanta with grenadine and bitters.', 1350000, 'Mocktails', 4),
  ('oso', 'Virgin Mojito', 'Fresh mint, lime, simple syrup and club soda.', 1350000, 'Mocktails', 5),
  ('oso', 'Winnie the Poo', 'Ginger juice, honey syrup and pineapple juice.', 1350000, 'Mocktails', 6),
  ('oso', 'Spicy Watermelon Mint', 'Watermelon, mint, lime, jalapeño and brown sugar.', 1350000, 'Mocktails', 7),
  ('oso', 'Lemon Ginger Spritz', 'Ginger, lemon juice, syrup and sparkling water.', 1350000, 'Mocktails', 8),
  ('oso', 'Lime Mint Mix', 'Lime juice and mint blend.', 1350000, 'Mocktails', 9),
  ('oso', 'Heineken Lager', 'The classic lager, poured cold in a special glass.', 1250000, 'Beers', 0),
  ('oso', 'Tiger Lager Beer', 'Fresh lager, poured cold in a special glass.', 1250000, 'Beers', 1),
  ('oso', 'Tango Beer', 'Your choice of lager mixed with grenadine syrup.', 1450000, 'Beers', 2),
  ('oso', 'Punchy Stout', 'Cold stout and coke, served in a special glass.', 1450000, 'Beers', 3),
  ('oso', 'Ginger Ale', 'Equal parts lager and ginger beer.', 1480000, 'Beers', 4),
  ('oso', 'La Fiole Côtes du Rhône Rosé', 'Fruity and round, 70% Grenache. Origin: France.', 11050000, 'Rosé Wines', 0),
  ('oso', 'Whispering Angel Rosé', 'Light, full-bodied with bright berry flavours. Origin: France.', 12500000, 'Rosé Wines', 1),
  ('oso', 'Mouton Cadet Sauvignon Blanc', 'Expressive and fruity, crisp citrus and white peach. Origin: France.', 9250000, 'White Wines', 0),
  ('oso', 'Art de Vivre White', 'Fresh, elegant and harmonious — perfect as an aperitif or with fish. Origin: France.', 8450000, 'White Wines', 1),
  ('oso', 'Escudo Rojo Sauvignon Blanc', 'White blossom, citrus and light tropical fruit. Origin: Chile.', 11550000, 'White Wines', 2),
  ('oso', 'Escudo Rojo Chardonnay', 'Pear, mango and pineapple, followed by toasted hazelnut. Origin: Chile.', 11850000, 'White Wines', 3),
  ('oso', 'Côtes des Roses Chardonnay', 'Citrus and white flowers with hints of pear and pineapple. Origin: France.', 10850000, 'White Wines', 4),
  ('oso', 'Domaine Garenne Sancerre Blanc', 'Crisp and mineral with citrus notes. Origin: France.', 12500000, 'White Wines', 5),
  ('oso', 'Cloudy Bay Sauvignon Blanc', 'Grapefruit aroma with a touch of pepper. Origin: New Zealand.', 21000000, 'White Wines', 6),
  ('oso', 'La Fiole Côtes du Rhône Red', 'Fruity and round with character, 70% Grenache. Origin: France.', 8950000, 'Red Wines', 0),
  ('oso', 'Mouton Cadet Bordeaux', 'Black cherry, black plum and blackcurrant. Origin: France.', 9500000, 'Red Wines', 1),
  ('oso', 'Mouton Cadet Réserve St-Émilion', 'Fruity, refined mature Merlot with a creamy tannic structure. Origin: France.', 10450000, 'Red Wines', 2),
  ('oso', 'La Fiole Châteauneuf du Pape', 'Elegant and ample, aged in 100-year-old oak casks. Origin: France.', 23500000, 'Red Wines', 3),
  ('oso', 'Mouton Cadet Réserve Graves', 'Oak, vanilla, blackcurrant and red fruits. Origin: France.', 11850000, 'Red Wines', 4),
  ('oso', 'Maison J. Grandet Rouge', 'Balanced and mildly sweet — for the lighter drinker. Origin: France.', 4850000, 'Red Wines', 5),
  ('oso', 'Escudo Rojo Gran Reserva', 'Ripe red and black fruit with caramel and mocha notes. Origin: Chile.', 12000000, 'Red Wines', 6),
  ('oso', 'Cloudy Bay Pinot Noir', 'Dark berries, silky length and dark chocolate tones. Origin: New Zealand.', 22500000, 'Red Wines', 7),
  ('oso', 'Château d''Arcins', 'Oak and vanilla with hints of blackcurrant, velvety with nice tannins. Origin: France.', 22800000, 'Red Wines', 8),
  ('oso', 'Escudo Rojo Luminoso (1.5 litre)', 'Jumbo bottle — ripe red fruits, berries, coffee and nuts. To share. Origin: Chile.', 22000000, 'Red Wines', 9),
  ('oso', 'Pierre Grandet Champagne Brut', null, 15000000, 'Champagnes', 0),
  ('oso', 'Pierre Grandet Champagne Rosé', null, 16000000, 'Champagnes', 1),
  ('oso', 'Luc Belaire Luxe Phantom', null, 19500000, 'Champagnes', 2),
  ('oso', 'Luc Belaire Gold, Blue or White', null, 19500000, 'Champagnes', 3),
  ('oso', 'Canard-Duchêne Charles VII Brut', null, 22500000, 'Champagnes', 4),
  ('oso', 'Canard-Duchêne Charles VII Rosé', null, 26000000, 'Champagnes', 5),
  ('oso', 'Canard-Duchêne Ch. VII Blanc de Blanc', null, 27500000, 'Champagnes', 6),
  ('oso', 'G.H. Mumm Demi-Sec', null, 29250000, 'Champagnes', 7),
  ('oso', 'Moët & Chandon Brut Impérial', null, 32500000, 'Champagnes', 8),
  ('oso', 'Moët & Chandon Nectar Impérial Blanc', null, 34000000, 'Champagnes', 9),
  ('oso', 'Moët & Chandon Nectar Impérial Rosé', null, 35500000, 'Champagnes', 10),
  ('oso', 'Veuve Clicquot Brut Yellow Label', null, 34500000, 'Champagnes', 11),
  ('oso', 'Veuve Clicquot Rosé', null, 38500000, 'Champagnes', 12),
  ('oso', 'Ruinart Blanc de Blancs', null, 55500000, 'Champagnes', 13),
  ('oso', 'Armand de Brignac Ace of Spades Brut', null, 136500000, 'Champagnes', 14),
  ('oso', 'Dom Pérignon Brut', null, 120000000, 'Champagnes', 15),
  ('oso', 'Dom Pérignon Rosé', null, 195000000, 'Champagnes', 16),
  ('oso', 'Martini Bianco', null, 5800000, 'Aperitifs & Digestifs', 0),
  ('oso', 'Martini Rosso', null, 5500000, 'Aperitifs & Digestifs', 1),
  ('oso', 'Cointreau', null, 10550000, 'Aperitifs & Digestifs', 2),
  ('oso', 'Campari', null, 8200000, 'Aperitifs & Digestifs', 3),
  ('oso', 'Bombay Sapphire Gin', null, 7500000, 'Tequila & Gin', 0),
  ('oso', 'Oriki African Infused Dry Gin', null, 9000000, 'Tequila & Gin', 1),
  ('oso', 'Olmeca Bianco Tequila', null, 9980000, 'Tequila & Gin', 2),
  ('oso', 'Salamanca Tequila', null, 18000000, 'Tequila & Gin', 3),
  ('oso', 'Volcan de mi Tierra Blanco', null, 24500000, 'Tequila & Gin', 4),
  ('oso', '818 Tequila Blanco', null, 27000000, 'Tequila & Gin', 5),
  ('oso', '818 Tequila Reposado', null, 31000000, 'Tequila & Gin', 6),
  ('oso', '818 Tequila Añejo', null, 39200000, 'Tequila & Gin', 7),
  ('oso', 'Casa Maestri Tequila Blanco', null, 33000000, 'Tequila & Gin', 8),
  ('oso', 'Casa Maestri Tequila Reposado', null, 46000000, 'Tequila & Gin', 9),
  ('oso', 'Don Julio Blanco', null, 43200000, 'Tequila & Gin', 10),
  ('oso', 'Don Julio Reposado', null, 44500000, 'Tequila & Gin', 11),
  ('oso', 'Casamigos Tequila Blanco', null, 34500000, 'Tequila & Gin', 12),
  ('oso', 'Casamigos Tequila Reposado', null, 35500000, 'Tequila & Gin', 13),
  ('oso', 'Eight Reserve Tequila', null, 97500000, 'Tequila & Gin', 14),
  ('oso', 'Don Julio 1942', null, 107500000, 'Tequila & Gin', 15),
  ('oso', 'Clase Azul Tequila', null, 123500000, 'Tequila & Gin', 16),
  ('oso', 'Cîroc Vodka Plain', null, 15000000, 'Vodka', 0),
  ('oso', 'Cîroc Vodka Flavoured', null, 16000000, 'Vodka', 1),
  ('oso', 'Belvedere Luminous Vodka', null, 18500000, 'Vodka', 2),
  ('oso', 'Grey Goose Essence Vodka', null, 16500000, 'Vodka', 3),
  ('oso', 'Hennessy VSOP', null, 33500000, 'Cognacs', 0),
  ('oso', 'Martell Blue Swift VSOP', null, 28500000, 'Cognacs', 1),
  ('oso', 'Martell XO', null, 105000000, 'Cognacs', 2),
  ('oso', 'Hennessy XO', null, 111000000, 'Cognacs', 3),
  ('oso', 'Glenmorangie 14 Yrs', null, 23500000, 'Single Malt Scotch Whiskeys', 0),
  ('oso', 'The Balvenie 14 Yrs Caribbean', null, 43500000, 'Single Malt Scotch Whiskeys', 1),
  ('oso', 'The Glenlivet 15 Yrs', null, 29000000, 'Single Malt Scotch Whiskeys', 2),
  ('oso', 'Glenfiddich 15 Yrs', null, 24700000, 'Single Malt Scotch Whiskeys', 3),
  ('oso', 'The Singleton 15 Yrs', null, 30500000, 'Single Malt Scotch Whiskeys', 4),
  ('oso', 'Macallan 15 Yrs', null, 55000000, 'Single Malt Scotch Whiskeys', 5),
  ('oso', 'Lagavulin 16 Yrs', null, 75000000, 'Single Malt Scotch Whiskeys', 6),
  ('oso', 'Glenfiddich 18 Yrs', null, 34900000, 'Single Malt Scotch Whiskeys', 7),
  ('oso', 'The Singleton 18 Yrs', null, 39800000, 'Single Malt Scotch Whiskeys', 8),
  ('oso', 'The Glenlivet 18 Yrs', null, 45000000, 'Single Malt Scotch Whiskeys', 9),
  ('oso', 'Glenmorangie 18 Yrs', null, 51000000, 'Single Malt Scotch Whiskeys', 10),
  ('oso', 'Macallan 18 Yrs', null, 99800000, 'Single Malt Scotch Whiskeys', 11),
  ('oso', 'Glenfiddich Gran Reserva 21 Yrs', null, 98800000, 'Single Malt Scotch Whiskeys', 12),
  ('oso', 'The Glenlivet 21 Yrs', null, 99500000, 'Single Malt Scotch Whiskeys', 13),
  ('oso', 'The Balvenie Portwood 21 Yrs', null, 115500000, 'Single Malt Scotch Whiskeys', 14),
  ('oso', 'Glenfiddich Grand Cru 23 Yrs', null, 137500000, 'Single Malt Scotch Whiskeys', 15),
  ('oso', 'Monkey Shoulder Batch 27', null, 14000000, 'Blended Scotch Whiskeys', 0),
  ('oso', 'Johnnie Walker 18 Yrs', null, 43500000, 'Blended Scotch Whiskeys', 1),
  ('oso', 'Johnnie Walker Blue Label', null, 107800000, 'Blended Scotch Whiskeys', 2),
  ('oso', 'Jack Daniel''s Old No. 7', null, 10500000, 'Irish, Japanese Whiskeys & Bourbons', 0),
  ('oso', 'Teeling Single Grain Irish Whiskey', null, 17200000, 'Irish, Japanese Whiskeys & Bourbons', 1),
  ('oso', 'Teeling Single Malt Irish Whiskey', null, 22500000, 'Irish, Japanese Whiskeys & Bourbons', 2),
  ('oso', 'Kamiki Japanese Blended Malt', null, 29950000, 'Irish, Japanese Whiskeys & Bourbons', 3),
  ('oso', 'Teeling Single Malt 21 Years', null, 87500000, 'Irish, Japanese Whiskeys & Bourbons', 4),
  ('oso', 'Mimosa Pitcher', 'Perfectly dosed to serve up to 4.', 6500000, 'Pitchers', 0),
  ('oso', 'Margarita Pitcher', 'Your choice of margarita flavour, in a pitcher (not frozen).', 6500000, 'Pitchers', 1),
  ('oso', 'Gin Basil Smash Pitcher', 'The balanced gin basil smash, for a small group.', 6000000, 'Pitchers', 2),
  ('oso', 'Sangria Lemonade Pitcher', 'Wine, lemonade and light rum infused with berries, orange and apple.', 6000000, 'Pitchers', 3),
  ('oso', 'Cranberry Juice Pitcher', 'Cranberry, lemonade, ice, orange and mint. Non-alcoholic.', 3600000, 'Pitchers', 4),
  ('oso', 'Pineapple Orange Pitcher', 'Orange, pineapple, lime and sprite, served cold.', 3600000, 'Pitchers', 5),
  ('oso', 'Apple Cinnamon Pitcher', 'Apple juice, apple slices, cinnamon sticks and ice.', 3750000, 'Pitchers', 6),
  ('oso', 'Tequila Shot', 'Tequila in a shot glass with salt and lime.', 720000, 'Shooters', 0),
  ('oso', 'Whiskey Shot', null, 850000, 'Shooters', 1),
  ('oso', 'Irish Car Bomb', 'Guinness, Irish cream and Irish whiskey.', 1200000, 'Shooters', 2),
  ('oso', 'Beam Me Up Scotty', 'Coffee liqueur, banana liqueur and Irish cream.', 1200000, 'Shooters', 3),
  ('oso', 'Oso''s Bazooka', 'Irish cream, blue curaçao and banana liqueur.', 1200000, 'Shooters', 4),
  ('oso', 'B-52 Shot', 'Kahlúa, Bailey''s and Grand Marnier.', 1200000, 'Shooters', 5),
  ('oso', 'Coke / Pepsi / Fanta / Mirinda', null, 380000, 'Fizzy Drinks', 0),
  ('oso', 'Sprite / Mtn Dew / Tonic Water', null, 420000, 'Fizzy Drinks', 1),
  ('oso', 'Still Bottled Water', null, 380000, 'Water, Juices & Energy Drinks', 0),
  ('oso', 'Freshly Squeezed Juice', null, 1000000, 'Water, Juices & Energy Drinks', 1),
  ('oso', 'Fresh Juice Mix (2 flavours)', null, 1260000, 'Water, Juices & Energy Drinks', 2),
  ('oso', 'Red Bull', null, 850000, 'Water, Juices & Energy Drinks', 3),
  ('oso', 'Voss Sparkling Lemon Cucumber Water', null, 900000, 'Water, Juices & Energy Drinks', 4),
  ('oso', 'Voss Sparkling Tangerine Lemongrass Water', null, 950000, 'Water, Juices & Energy Drinks', 5),
  ('oso', 'Black Coffee', null, 800000, 'Coffee, Tea & Shakes', 0),
  ('oso', 'Tea Pot', null, 800000, 'Coffee, Tea & Shakes', 1),
  ('oso', 'Espresso', null, 850000, 'Coffee, Tea & Shakes', 2),
  ('oso', 'Cappuccino', null, 850000, 'Coffee, Tea & Shakes', 3),
  ('oso', 'Hot / Cold Chocolate', null, 850000, 'Coffee, Tea & Shakes', 4),
  ('oso', 'Chai Latte', null, 1000000, 'Coffee, Tea & Shakes', 5),
  ('oso', 'Milk Shake', null, 1100000, 'Coffee, Tea & Shakes', 6),
  ('oso', 'Arabic Chai Pot', null, 1150000, 'Coffee, Tea & Shakes', 7),
  ('bbr', 'G.H. Mumm Grand Cordon', null, 22050000, 'Champagnes', 0),
  ('bbr', 'Canard-Duchêne C.VII Brut', null, 25200000, 'Champagnes', 1),
  ('bbr', 'G.H. Mumm Demi-Sec', null, 25830000, 'Champagnes', 2),
  ('bbr', 'Canard-Duchêne C.VII Rosé', null, 29400000, 'Champagnes', 3),
  ('bbr', 'Canard-Duchêne C.VII Blanc de Blanc', null, 30450000, 'Champagnes', 4),
  ('bbr', 'Moët & Chandon Nectar Impérial Brut', null, 33600000, 'Champagnes', 5),
  ('bbr', 'Moët & Chandon Nectar Impérial Blanc', null, 35700000, 'Champagnes', 6),
  ('bbr', 'Moët & Chandon Nectar Impérial Rosé', null, 37800000, 'Champagnes', 7),
  ('bbr', 'Veuve Clicquot Brut Yellow Label', null, 37800000, 'Champagnes', 8),
  ('bbr', 'Veuve Clicquot Rosé', null, 40950000, 'Champagnes', 9),
  ('bbr', 'Ruinart Blanc de Blancs', null, 49875000, 'Champagnes', 10),
  ('bbr', 'Krug Champagne Grande Cuvée Brut', null, 126000000, 'Champagnes', 11),
  ('bbr', 'Dom Pérignon Brut', null, 127050000, 'Champagnes', 12),
  ('bbr', 'Krug Champagne Rosé', null, 141750000, 'Champagnes', 13),
  ('bbr', 'Armand de Brignac Ace of Spades Brut', null, 157500000, 'Champagnes', 14),
  ('bbr', 'Armand de Brignac Ace of Spades Rosé', null, 173250000, 'Champagnes', 15),
  ('bbr', 'Dom Pérignon Rosé', null, 299250000, 'Champagnes', 16),
  ('bbr', 'Salamanca Tequila', null, 26250000, 'Tequila', 0),
  ('bbr', '818 Tequila Blanco', null, 28875000, 'Tequila', 1),
  ('bbr', '818 Tequila Reposado', null, 34125000, 'Tequila', 2),
  ('bbr', '818 Tequila Añejo', null, 40950000, 'Tequila', 3),
  ('bbr', 'Don Julio Tequila Blanco', null, 35175000, 'Tequila', 4),
  ('bbr', 'Don Julio Reposado', null, 36750000, 'Tequila', 5),
  ('bbr', 'Casa Maestri Tequila', null, 39690000, 'Tequila', 6),
  ('bbr', 'Casamigos Tequila Blanco', null, 42525000, 'Tequila', 7),
  ('bbr', 'Casamigos Tequila Reposado', null, 43575000, 'Tequila', 8),
  ('bbr', 'Eight Reserve Tequila', null, 85575000, 'Tequila', 9),
  ('bbr', 'Don Julio 1942', null, 93450000, 'Tequila', 10),
  ('bbr', 'Clase Azul Tequila Reposado', null, 152250000, 'Tequila', 11),
  ('bbr', 'Cîroc Vodka Plain', null, 20475000, 'Vodka', 0),
  ('bbr', 'Cîroc Vodka Flavoured', null, 21000000, 'Vodka', 1),
  ('bbr', 'Grey Goose Essence Vodka', null, 21000000, 'Vodka', 2),
  ('bbr', 'Hennessy VSOP', null, 35175000, 'Cognacs', 0),
  ('bbr', 'Martell Blue Swift VSOP', null, 30975000, 'Cognacs', 1),
  ('bbr', 'Martell XO', null, 99750000, 'Cognacs', 2),
  ('bbr', 'Hennessy XO', null, 115500000, 'Cognacs', 3),
  ('bbr', 'Richard Hennessy', null, 682500000, 'Cognacs', 4),
  ('bbr', 'The Singleton 15 Yrs', null, 24675000, 'Single Malt Scotch Whiskeys', 0),
  ('bbr', 'Glenfiddich 15 Yrs Solera', null, 25725000, 'Single Malt Scotch Whiskeys', 1),
  ('bbr', 'Chivas Regal 18 Yrs', null, 25725000, 'Single Malt Scotch Whiskeys', 2),
  ('bbr', 'Glenlivet 15 Yrs', null, 29925000, 'Single Malt Scotch Whiskeys', 3),
  ('bbr', 'Glenfiddich 18 Yrs Speyside', null, 38325000, 'Single Malt Scotch Whiskeys', 4),
  ('bbr', 'The Singleton 18 Yrs', null, 41475000, 'Single Malt Scotch Whiskeys', 5),
  ('bbr', 'Glenlivet 18 Yrs', null, 51450000, 'Single Malt Scotch Whiskeys', 6),
  ('bbr', 'Macallan 15 Yrs', null, 59850000, 'Single Malt Scotch Whiskeys', 7),
  ('bbr', 'Lagavulin 16 Yrs', null, 76650000, 'Single Malt Scotch Whiskeys', 8),
  ('bbr', 'Glenfiddich Gran Reserva 21 Yrs', null, 110250000, 'Single Malt Scotch Whiskeys', 9),
  ('bbr', 'Macallan 18 Yrs', null, 115500000, 'Single Malt Scotch Whiskeys', 10),
  ('bbr', 'The Balvenie Portwood 21 Yrs', null, 128625000, 'Single Malt Scotch Whiskeys', 11),
  ('bbr', 'Glenfiddich Grand Cru 23 Yrs', null, 144375000, 'Single Malt Scotch Whiskeys', 12),
  ('bbr', 'Johnnie Walker Gold Label', null, 18900000, 'Blended Scotch Whiskeys', 0),
  ('bbr', 'Johnnie Walker 18 Yrs', null, 36225000, 'Blended Scotch Whiskeys', 1),
  ('bbr', 'Johnnie Walker Blue Label', null, 110250000, 'Blended Scotch Whiskeys', 2),
  ('bbr', 'Whisky Sour', null, 1650000, 'Cocktails', 0),
  ('bbr', 'Gin Tonic', null, 1650000, 'Cocktails', 1),
  ('bbr', 'Classic Mojito', null, 1650000, 'Cocktails', 2),
  ('bbr', 'Frozen Margarita', null, 1800000, 'Cocktails', 3),
  ('bbr', 'Long Island', null, 1800000, 'Cocktails', 4),
  ('bbr', 'Moscow Mule', null, 1800000, 'Cocktails', 5),
  ('bbr', 'Old Fashioned', null, 1800000, 'Cocktails', 6),
  ('bbr', 'Coconut Aperol Margarita', null, 1850000, 'Cocktails', 7),
  ('bbr', 'Kir Imperial', null, 2450000, 'Cocktails', 8),
  ('bbr', 'Kir Royal', null, 2650000, 'Cocktails', 9),
  ('bbr', 'Mimosa', null, 2650000, 'Cocktails', 10),
  ('bbr', 'Popcorn and Glazed Pistachios', null, 1200000, 'Lite Bites & Snacks', 0),
  ('bbr', 'Flavored Tortilla Chips and Aioli', null, 1200000, 'Lite Bites & Snacks', 1),
  ('bbr', 'Shrimp Spring Rolls', null, 1200000, 'Lite Bites & Snacks', 2),
  ('bbr', 'Chicken Quesadillas', null, 1500000, 'Lite Bites & Snacks', 3),
  ('bbr', 'Beef and Goat Meat Sliders', null, 1500000, 'Lite Bites & Snacks', 4),
  ('bbr', 'Classic Buffalo Wings', null, 1500000, 'Lite Bites & Snacks', 5),
  ('bbr', 'Toasted Chicken Wrap', null, 1800000, 'Lite Bites & Snacks', 6),
  ('bbr', 'Satay Chicken Skewers', null, 1800000, 'Lite Bites & Snacks', 7),
  ('bbr', 'Canadian Chicken Tenders', null, 1800000, 'Lite Bites & Snacks', 8),
  ('bbr', 'Fizzy Cans (coke, orange, sprite, dew)', 'Sold with a bottle only.', 315000, 'Mixers', 0),
  ('bbr', 'Still Water', 'Sold with a bottle only.', 472500, 'Mixers', 1),
  ('bbr', 'Red Bull Can', 'Sold with a bottle only.', 945000, 'Mixers', 2),
  ('bbr', 'Cranberry Pitcher', 'Sold with a bottle only.', 3675000, 'Mixers', 3),
  ('bbr', 'Fresh Juice Pitcher', 'Sold with a bottle only.', 3990000, 'Mixers', 4)
) as v(venue_slug, name, description, price_kobo, category, sort_order)
  join venues ven on ven.slug = v.venue_slug;
end
$seed$;
