-- ============================================================================
-- 0039 — Make sort_order carry the category sequence too.
--
-- 0037 defined sort_order as the position WITHIN a category, which orders the
-- items inside "Red Wines" correctly but says nothing about where Red Wines
-- sits relative to Champagnes. Nothing else in the row records that, so the
-- shop had no way to reproduce the menu's own sequence — starters before
-- mains, cocktails before spirits — and would have fallen back to listing
-- categories alphabetically.
--
-- Renumbering sort_order as a venue-global running position fixes that without
-- a second column: categories were seeded contiguously, so ordering by
-- (venue_id, sort_order) now yields the printed category order and the printed
-- order within each category at once.
-- ============================================================================

-- Venues by slug, not by production UUID — see 0038 for why.
update catalog_items c set sort_order = v.pos
from (values
  ('oso', 'Chicken Wings', 1),
  ('oso', 'Beef and Goat Meat Sliders', 2),
  ('oso', 'Smoked Chicken Quesadilla', 3),
  ('oso', 'Cheesy Chicken Lollipops', 4),
  ('oso', 'Shrimp Popcorn', 5),
  ('oso', 'Shrimp Spring Rolls', 6),
  ('oso', 'Tacos', 7),
  ('oso', 'Garlic Parm Chicken Skewers', 8),
  ('oso', 'Spicy Peppersoup', 9),
  ('oso', 'Soup of the Day', 10),
  ('oso', 'Chicken Caesar Salad', 11),
  ('oso', 'Seafood Salad', 12),
  ('oso', 'Oso''s Waldorf', 13),
  ('oso', 'Chicken Burrito Bowl', 14),
  ('oso', 'Hoisin Rice Bowl', 15),
  ('oso', 'Salmon Poke Bowl', 16),
  ('oso', 'Beef Egg Noodle Bowl', 17),
  ('oso', 'Chicken Bacon Club', 18),
  ('oso', 'Oso Burger Royale', 19),
  ('oso', 'Crispy Chicken Sandwich', 20),
  ('oso', 'Egg and Bacon Bagel', 21),
  ('oso', 'Breakfast Burrito', 22),
  ('oso', 'Stuffed Pita (Arayes)', 23),
  ('oso', 'Picante de Gallina', 24),
  ('oso', 'Rabo de Toro', 25),
  ('oso', 'Alitas de Pavo Picantes', 26),
  ('oso', 'Egg Fried Rice', 27),
  ('oso', 'Spicy Meatballs Spaghetti', 28),
  ('oso', 'Pasta Carbonara', 29),
  ('oso', 'Chicken Alfredo Pasta', 30),
  ('oso', 'Creamy Shrimp Fettuccine', 31),
  ('oso', 'Spicy Fish Linguini', 32),
  ('oso', 'Grilled Salmon Filet', 33),
  ('oso', 'Shrimp Boil Foil Pack', 34),
  ('oso', 'Grilled Jumbo Prawns', 35),
  ('oso', 'Sea Bass Filet', 36),
  ('oso', 'Honey Glazed BBQ Baby Chicken', 37),
  ('oso', 'Grilled Lamb Chops', 38),
  ('oso', 'Sweet and Savory Pork Belly', 39),
  ('oso', 'Spinach and Artichoke Stuffed Chicken Breasts', 40),
  ('oso', 'Beef Steak', 41),
  ('oso', 'Seafood Platter', 42),
  ('oso', 'Meat Platter', 43),
  ('oso', 'Steamed Basmati Rice', 44),
  ('oso', 'Steamed / Sautéed Vegetables', 45),
  ('oso', 'Fried Ripe Plantain', 46),
  ('oso', 'Oso''s Smoky Jollof', 47),
  ('oso', 'Crispy French Fries', 48),
  ('oso', 'Mashed Potatoes', 49),
  ('oso', 'Rice with Kidney Beans and Thyme', 50),
  ('oso', 'French Crêpes', 51),
  ('oso', 'Churros & Chocolate Dip', 52),
  ('oso', 'Sweet Puff Puff', 53),
  ('oso', 'Ice Cream Browny', 54),
  ('oso', 'Kir Imperial', 55),
  ('oso', 'Kir Royal', 56),
  ('oso', 'Peach Bellini', 57),
  ('oso', 'Mimosa', 58),
  ('oso', 'Mint Grapefruit Mimosa', 59),
  ('oso', 'Mint Julep', 60),
  ('oso', 'Gin Basil Smash', 61),
  ('oso', 'Negroni with a Twist', 62),
  ('oso', 'Beergarita', 63),
  ('oso', 'Classic Mojito', 64),
  ('oso', 'Long Island', 65),
  ('oso', 'Gin Tonic', 66),
  ('oso', 'Moscow Mule', 67),
  ('oso', 'The White Lady', 68),
  ('oso', 'Cosmopolitan', 69),
  ('oso', 'Whisky Sour', 70),
  ('oso', 'Old Fashioned', 71),
  ('oso', 'Aperol Spritz', 72),
  ('oso', 'Aperol Gin Twirl', 73),
  ('oso', 'Frozen Margarita', 74),
  ('oso', 'Frozen Daiquiri', 75),
  ('oso', 'Piña Colada', 76),
  ('oso', 'Obaje''s Honey Pot', 77),
  ('oso', 'Coconut Aperol Margarita', 78),
  ('oso', 'Missionary''s Downfall', 79),
  ('oso', 'Clear ''n'' Stormy', 80),
  ('oso', 'Whisky Ginger', 81),
  ('oso', 'Summer in Scotland', 82),
  ('oso', 'Run This Town', 83),
  ('oso', 'Indomitable Spirit', 84),
  ('oso', 'Oso''s Grog', 85),
  ('oso', 'Oso''s Quine', 86),
  ('oso', 'Oso''s Passion Delights', 87),
  ('oso', 'Orange Pineapple Punch', 88),
  ('oso', 'Chapman', 89),
  ('oso', 'Virgin Mojito', 90),
  ('oso', 'Winnie the Poo', 91),
  ('oso', 'Spicy Watermelon Mint', 92),
  ('oso', 'Lemon Ginger Spritz', 93),
  ('oso', 'Lime Mint Mix', 94),
  ('oso', 'Heineken Lager', 95),
  ('oso', 'Tiger Lager Beer', 96),
  ('oso', 'Tango Beer', 97),
  ('oso', 'Punchy Stout', 98),
  ('oso', 'Ginger Ale', 99),
  ('oso', 'La Fiole Côtes du Rhône Rosé', 100),
  ('oso', 'Whispering Angel Rosé', 101),
  ('oso', 'Mouton Cadet Sauvignon Blanc', 102),
  ('oso', 'Art de Vivre White', 103),
  ('oso', 'Escudo Rojo Sauvignon Blanc', 104),
  ('oso', 'Escudo Rojo Chardonnay', 105),
  ('oso', 'Côtes des Roses Chardonnay', 106),
  ('oso', 'Domaine Garenne Sancerre Blanc', 107),
  ('oso', 'Cloudy Bay Sauvignon Blanc', 108),
  ('oso', 'La Fiole Côtes du Rhône Red', 109),
  ('oso', 'Mouton Cadet Bordeaux', 110),
  ('oso', 'Mouton Cadet Réserve St-Émilion', 111),
  ('oso', 'La Fiole Châteauneuf du Pape', 112),
  ('oso', 'Mouton Cadet Réserve Graves', 113),
  ('oso', 'Maison J. Grandet Rouge', 114),
  ('oso', 'Escudo Rojo Gran Reserva', 115),
  ('oso', 'Cloudy Bay Pinot Noir', 116),
  ('oso', 'Château d''Arcins', 117),
  ('oso', 'Escudo Rojo Luminoso (1.5 litre)', 118),
  ('oso', 'Pierre Grandet Champagne Brut', 119),
  ('oso', 'Pierre Grandet Champagne Rosé', 120),
  ('oso', 'Luc Belaire Luxe Phantom', 121),
  ('oso', 'Luc Belaire Gold, Blue or White', 122),
  ('oso', 'Canard-Duchêne Charles VII Brut', 123),
  ('oso', 'Canard-Duchêne Charles VII Rosé', 124),
  ('oso', 'Canard-Duchêne Ch. VII Blanc de Blanc', 125),
  ('oso', 'G.H. Mumm Demi-Sec', 126),
  ('oso', 'Moët & Chandon Brut Impérial', 127),
  ('oso', 'Moët & Chandon Nectar Impérial Blanc', 128),
  ('oso', 'Moët & Chandon Nectar Impérial Rosé', 129),
  ('oso', 'Veuve Clicquot Brut Yellow Label', 130),
  ('oso', 'Veuve Clicquot Rosé', 131),
  ('oso', 'Ruinart Blanc de Blancs', 132),
  ('oso', 'Armand de Brignac Ace of Spades Brut', 133),
  ('oso', 'Dom Pérignon Brut', 134),
  ('oso', 'Dom Pérignon Rosé', 135),
  ('oso', 'Martini Bianco', 136),
  ('oso', 'Martini Rosso', 137),
  ('oso', 'Cointreau', 138),
  ('oso', 'Campari', 139),
  ('oso', 'Bombay Sapphire Gin', 140),
  ('oso', 'Oriki African Infused Dry Gin', 141),
  ('oso', 'Olmeca Bianco Tequila', 142),
  ('oso', 'Salamanca Tequila', 143),
  ('oso', 'Volcan de mi Tierra Blanco', 144),
  ('oso', '818 Tequila Blanco', 145),
  ('oso', '818 Tequila Reposado', 146),
  ('oso', '818 Tequila Añejo', 147),
  ('oso', 'Casa Maestri Tequila Blanco', 148),
  ('oso', 'Casa Maestri Tequila Reposado', 149),
  ('oso', 'Don Julio Blanco', 150),
  ('oso', 'Don Julio Reposado', 151),
  ('oso', 'Casamigos Tequila Blanco', 152),
  ('oso', 'Casamigos Tequila Reposado', 153),
  ('oso', 'Eight Reserve Tequila', 154),
  ('oso', 'Don Julio 1942', 155),
  ('oso', 'Clase Azul Tequila', 156),
  ('oso', 'Cîroc Vodka Plain', 157),
  ('oso', 'Cîroc Vodka Flavoured', 158),
  ('oso', 'Belvedere Luminous Vodka', 159),
  ('oso', 'Grey Goose Essence Vodka', 160),
  ('oso', 'Hennessy VSOP', 161),
  ('oso', 'Martell Blue Swift VSOP', 162),
  ('oso', 'Martell XO', 163),
  ('oso', 'Hennessy XO', 164),
  ('oso', 'Glenmorangie 14 Yrs', 165),
  ('oso', 'The Balvenie 14 Yrs Caribbean', 166),
  ('oso', 'The Glenlivet 15 Yrs', 167),
  ('oso', 'Glenfiddich 15 Yrs', 168),
  ('oso', 'The Singleton 15 Yrs', 169),
  ('oso', 'Macallan 15 Yrs', 170),
  ('oso', 'Lagavulin 16 Yrs', 171),
  ('oso', 'Glenfiddich 18 Yrs', 172),
  ('oso', 'The Singleton 18 Yrs', 173),
  ('oso', 'The Glenlivet 18 Yrs', 174),
  ('oso', 'Glenmorangie 18 Yrs', 175),
  ('oso', 'Macallan 18 Yrs', 176),
  ('oso', 'Glenfiddich Gran Reserva 21 Yrs', 177),
  ('oso', 'The Glenlivet 21 Yrs', 178),
  ('oso', 'The Balvenie Portwood 21 Yrs', 179),
  ('oso', 'Glenfiddich Grand Cru 23 Yrs', 180),
  ('oso', 'Monkey Shoulder Batch 27', 181),
  ('oso', 'Johnnie Walker 18 Yrs', 182),
  ('oso', 'Johnnie Walker Blue Label', 183),
  ('oso', 'Jack Daniel''s Old No. 7', 184),
  ('oso', 'Teeling Single Grain Irish Whiskey', 185),
  ('oso', 'Teeling Single Malt Irish Whiskey', 186),
  ('oso', 'Kamiki Japanese Blended Malt', 187),
  ('oso', 'Teeling Single Malt 21 Years', 188),
  ('oso', 'Mimosa Pitcher', 189),
  ('oso', 'Margarita Pitcher', 190),
  ('oso', 'Gin Basil Smash Pitcher', 191),
  ('oso', 'Sangria Lemonade Pitcher', 192),
  ('oso', 'Cranberry Juice Pitcher', 193),
  ('oso', 'Pineapple Orange Pitcher', 194),
  ('oso', 'Apple Cinnamon Pitcher', 195),
  ('oso', 'Tequila Shot', 196),
  ('oso', 'Whiskey Shot', 197),
  ('oso', 'Irish Car Bomb', 198),
  ('oso', 'Beam Me Up Scotty', 199),
  ('oso', 'Oso''s Bazooka', 200),
  ('oso', 'B-52 Shot', 201),
  ('oso', 'Coke / Pepsi / Fanta / Mirinda', 202),
  ('oso', 'Sprite / Mtn Dew / Tonic Water', 203),
  ('oso', 'Still Bottled Water', 204),
  ('oso', 'Freshly Squeezed Juice', 205),
  ('oso', 'Fresh Juice Mix (2 flavours)', 206),
  ('oso', 'Red Bull', 207),
  ('oso', 'Voss Sparkling Lemon Cucumber Water', 208),
  ('oso', 'Voss Sparkling Tangerine Lemongrass Water', 209),
  ('oso', 'Black Coffee', 210),
  ('oso', 'Tea Pot', 211),
  ('oso', 'Espresso', 212),
  ('oso', 'Cappuccino', 213),
  ('oso', 'Hot / Cold Chocolate', 214),
  ('oso', 'Chai Latte', 215),
  ('oso', 'Milk Shake', 216),
  ('oso', 'Arabic Chai Pot', 217),
  ('bbr', 'G.H. Mumm Grand Cordon', 1),
  ('bbr', 'Canard-Duchêne C.VII Brut', 2),
  ('bbr', 'G.H. Mumm Demi-Sec', 3),
  ('bbr', 'Canard-Duchêne C.VII Rosé', 4),
  ('bbr', 'Canard-Duchêne C.VII Blanc de Blanc', 5),
  ('bbr', 'Moët & Chandon Nectar Impérial Brut', 6),
  ('bbr', 'Moët & Chandon Nectar Impérial Blanc', 7),
  ('bbr', 'Moët & Chandon Nectar Impérial Rosé', 8),
  ('bbr', 'Veuve Clicquot Brut Yellow Label', 9),
  ('bbr', 'Veuve Clicquot Rosé', 10),
  ('bbr', 'Ruinart Blanc de Blancs', 11),
  ('bbr', 'Krug Champagne Grande Cuvée Brut', 12),
  ('bbr', 'Dom Pérignon Brut', 13),
  ('bbr', 'Krug Champagne Rosé', 14),
  ('bbr', 'Armand de Brignac Ace of Spades Brut', 15),
  ('bbr', 'Armand de Brignac Ace of Spades Rosé', 16),
  ('bbr', 'Dom Pérignon Rosé', 17),
  ('bbr', 'Salamanca Tequila', 18),
  ('bbr', '818 Tequila Blanco', 19),
  ('bbr', '818 Tequila Reposado', 20),
  ('bbr', '818 Tequila Añejo', 21),
  ('bbr', 'Don Julio Tequila Blanco', 22),
  ('bbr', 'Don Julio Reposado', 23),
  ('bbr', 'Casa Maestri Tequila', 24),
  ('bbr', 'Casamigos Tequila Blanco', 25),
  ('bbr', 'Casamigos Tequila Reposado', 26),
  ('bbr', 'Eight Reserve Tequila', 27),
  ('bbr', 'Don Julio 1942', 28),
  ('bbr', 'Clase Azul Tequila Reposado', 29),
  ('bbr', 'Cîroc Vodka Plain', 30),
  ('bbr', 'Cîroc Vodka Flavoured', 31),
  ('bbr', 'Grey Goose Essence Vodka', 32),
  ('bbr', 'Hennessy VSOP', 33),
  ('bbr', 'Martell Blue Swift VSOP', 34),
  ('bbr', 'Martell XO', 35),
  ('bbr', 'Hennessy XO', 36),
  ('bbr', 'Richard Hennessy', 37),
  ('bbr', 'The Singleton 15 Yrs', 38),
  ('bbr', 'Glenfiddich 15 Yrs Solera', 39),
  ('bbr', 'Chivas Regal 18 Yrs', 40),
  ('bbr', 'Glenlivet 15 Yrs', 41),
  ('bbr', 'Glenfiddich 18 Yrs Speyside', 42),
  ('bbr', 'The Singleton 18 Yrs', 43),
  ('bbr', 'Glenlivet 18 Yrs', 44),
  ('bbr', 'Macallan 15 Yrs', 45),
  ('bbr', 'Lagavulin 16 Yrs', 46),
  ('bbr', 'Glenfiddich Gran Reserva 21 Yrs', 47),
  ('bbr', 'Macallan 18 Yrs', 48),
  ('bbr', 'The Balvenie Portwood 21 Yrs', 49),
  ('bbr', 'Glenfiddich Grand Cru 23 Yrs', 50),
  ('bbr', 'Johnnie Walker Gold Label', 51),
  ('bbr', 'Johnnie Walker 18 Yrs', 52),
  ('bbr', 'Johnnie Walker Blue Label', 53),
  ('bbr', 'Whisky Sour', 54),
  ('bbr', 'Gin Tonic', 55),
  ('bbr', 'Classic Mojito', 56),
  ('bbr', 'Frozen Margarita', 57),
  ('bbr', 'Long Island', 58),
  ('bbr', 'Moscow Mule', 59),
  ('bbr', 'Old Fashioned', 60),
  ('bbr', 'Coconut Aperol Margarita', 61),
  ('bbr', 'Kir Imperial', 62),
  ('bbr', 'Kir Royal', 63),
  ('bbr', 'Mimosa', 64),
  ('bbr', 'Popcorn and Glazed Pistachios', 65),
  ('bbr', 'Flavored Tortilla Chips and Aioli', 66),
  ('bbr', 'Shrimp Spring Rolls', 67),
  ('bbr', 'Chicken Quesadillas', 68),
  ('bbr', 'Beef and Goat Meat Sliders', 69),
  ('bbr', 'Classic Buffalo Wings', 70),
  ('bbr', 'Toasted Chicken Wrap', 71),
  ('bbr', 'Satay Chicken Skewers', 72),
  ('bbr', 'Canadian Chicken Tenders', 73),
  ('bbr', 'Fizzy Cans (coke, orange, sprite, dew)', 74),
  ('bbr', 'Still Water', 75),
  ('bbr', 'Red Bull Can', 76),
  ('bbr', 'Cranberry Pitcher', 77),
  ('bbr', 'Fresh Juice Pitcher', 78)
) as v(venue_slug, name, pos)
join venues ven on ven.slug = v.venue_slug
where c.venue_id = ven.id and c.name = v.name;

-- The Cap is merchandise, not a menu section, so it sits after the menu.
update catalog_items set sort_order = 9000
 where name = 'Kamadeva Privé Cap';

comment on column catalog_items.sort_order is
  'Position in the venue''s printed menu, counted across the whole menu rather '
  'than restarting per category, so ordering by it reproduces both the category '
  'sequence and the order of items within each category.';
