-- ============================================================================
-- 0045 — Recurring events: a rule, the occurrences it produces, and the notice
--        members get.
--
-- An event is not just a date on a page. reservations, visits, transactions,
-- discount_designations, event_access_windows and muse.event_calendar all carry
-- a foreign key to events(id). A "virtual" occurrence computed at read time
-- could not be booked, attended, charged against or discounted — so every
-- occurrence here is a REAL events row, and the recurrence rule lives beside
-- them in its own table rather than being smeared across the rows it generates.
--
-- Three moving parts:
--   event_series          the rule — what recurs, how often, until when
--   materialise_event_series   turns the rule into events rows, up to a horizon
--   announce_due_events   posts each occurrence to members before it happens
--
-- Materialising is idempotent on (series_id, occurrence_date). That single
-- unique index does the work of a lock: the job can run twice, the horizon can
-- overlap, and nothing is ever created twice. It also means a cancelled
-- occurrence STAYS cancelled — the row still exists, so the next run skips it
-- instead of quietly resurrecting an evening the venue called off.
-- ============================================================================

create type event_recurrence as enum ('daily', 'weekly', 'monthly');

create table event_series (
  id                   uuid primary key default gen_random_uuid(),
  venue_id             uuid references venues(id) on delete restrict,
  name                 text not null check (length(trim(name)) >= 2),
  recurrence           event_recurrence not null,
  -- Every N days/weeks/months. 1 is the ordinary case; 2 gives fortnightly.
  every_n              int not null default 1 check (every_n between 1 and 52),
  -- The first occurrence, and the anchor every later one is measured from.
  starts_on            date not null,
  -- Local wall-clock time at the venue. Stored apart from the date so that a
  -- 9pm event stays 9pm on every occurrence rather than drifting with offsets.
  time_of_day          time not null,
  duration_minutes     int check (duration_minutes is null or duration_minutes between 15 and 1440),
  until                date,                      -- null = open-ended
  capacity             int,
  min_reservation_tier tier_enum,
  status               text not null default 'published'
                         check (status in ('draft', 'published', 'cancelled')),
  -- Whether members are told, and how far ahead.
  announce             boolean not null default true,
  announce_days_before int not null default 1 check (announce_days_before between 0 and 30),
  announce_audience    text not null default 'all'
                         check (announce_audience in ('all', 'prive', 'muse')),
  created_by           uuid not null references staff_profiles(id),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint event_series_until_after_start check (until is null or until >= starts_on)
);

create trigger event_series_touch
  before update on event_series
  for each row execute function touch_updated_at();

alter table event_series enable row level security;

create policy event_series_staff_read on event_series for select to authenticated
  using (is_staff());
revoke insert, update, delete on event_series from anon, authenticated;

-- Occurrences point back at the rule that made them.
alter table events
  add column if not exists series_id       uuid references event_series(id) on delete set null,
  add column if not exists occurrence_date date,
  add column if not exists announced_at    timestamptz;

-- The idempotency guarantee. Partial, so one-off events are unaffected.
create unique index if not exists events_series_occurrence_idx
  on events (series_id, occurrence_date)
  where series_id is not null;

comment on column events.series_id is
  'Set when this event was generated by an event_series. Null for one-offs.';
comment on column events.announced_at is
  'When members were notified. Null means not yet announced; set once, so a
   re-run of announce_due_events cannot notify the same evening twice.';

-- ── Creating a rule ─────────────────────────────────────────────────────────

create or replace function create_event_series(
  p_name                 text,
  p_recurrence           event_recurrence,
  p_starts_on            date,
  p_time_of_day          time,
  p_venue_id             uuid    default null,
  p_every_n              int     default 1,
  p_until                date    default null,
  p_duration_minutes     int     default null,
  p_capacity             int     default null,
  p_min_reservation_tier tier_enum default null,
  p_status               text    default 'published',
  p_announce             boolean default true,
  p_announce_days_before int     default 1,
  p_announce_audience    text    default 'all'
)
returns event_series
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_staff uuid := current_staff_id();
  v_series event_series%rowtype;
begin
  -- Same gate as save_event: a positive allow-list, since current_staff_role()
  -- is null for a non-staff caller and a negated test would let that through.
  if current_staff_role() is null
     or current_staff_role() not in ('venue_manager', 'hosl', 'founder') then
    raise exception 'events are managed by venue managers and above';
  end if;
  if p_venue_id is not null and not staff_has_venue(p_venue_id) then
    raise exception 'no active assignment at this venue';
  end if;
  if p_status not in ('draft', 'published', 'cancelled') then
    raise exception 'status must be draft, published, or cancelled';
  end if;

  insert into event_series (
    venue_id, name, recurrence, every_n, starts_on, time_of_day, duration_minutes,
    until, capacity, min_reservation_tier, status,
    announce, announce_days_before, announce_audience, created_by
  ) values (
    p_venue_id, trim(p_name), p_recurrence, coalesce(p_every_n, 1), p_starts_on,
    p_time_of_day, p_duration_minutes, p_until, p_capacity, p_min_reservation_tier,
    p_status, coalesce(p_announce, true), coalesce(p_announce_days_before, 1),
    coalesce(p_announce_audience, 'all'), v_staff
  ) returning * into v_series;

  -- Fill the calendar straight away, so the person who just set this up can see
  -- the dates rather than waiting for tonight's job.
  perform materialise_event_series(60, v_series.id);

  perform log_audit(
    p_actor_type => 'staff'::actor_type,
    p_actor_id   => v_staff,
    p_action     => 'event_series.create',
    p_entity_type=> 'event_series',
    p_entity_id  => v_series.id::text,
    p_venue_id   => p_venue_id,
    p_after      => to_jsonb(v_series)
  );

  return v_series;
end;
$$;

-- ── Turning rules into dates ────────────────────────────────────────────────

create or replace function materialise_event_series(
  p_horizon_days int  default 60,
  p_series_id    uuid default null
)
returns int
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  s          event_series%rowtype;
  v_horizon  date := current_date + greatest(coalesce(p_horizon_days, 60), 1);
  v_date     date;
  v_starts   timestamptz;
  v_created  int := 0;
  i          int;
begin
  for s in
    select * from event_series
     where status <> 'cancelled'
       and (p_series_id is null or id = p_series_id)
  loop
    i := 0;
    loop
      -- Always measured from the anchor, never from the previous occurrence.
      -- Stepping month by month would drift: the 31st clamps to the 28th in
      -- February and then stays on the 28th forever. From the anchor,
      -- Jan 31 + 2 months is March 31 again.
      v_date := case s.recurrence
                  when 'daily'   then s.starts_on + ((i * s.every_n) || ' days')::interval
                  when 'weekly'  then s.starts_on + ((i * s.every_n) || ' weeks')::interval
                  when 'monthly' then s.starts_on + ((i * s.every_n) || ' months')::interval
                end::date;

      exit when v_date > v_horizon;
      exit when s.until is not null and v_date > s.until;
      i := i + 1;
      exit when i > 2000;  -- backstop; a daily series cannot outrun this

      if v_date >= current_date then
        -- Compose the instant in the venue's own wall clock, so 9pm is 9pm on
        -- every occurrence.
        v_starts := (v_date + s.time_of_day) at time zone 'Africa/Lagos';

        insert into events (
          venue_id, name, starts_at, ends_at, capacity, status,
          min_reservation_tier, created_by, series_id, occurrence_date
        ) values (
          s.venue_id, s.name, v_starts,
          case when s.duration_minutes is null then null
               else v_starts + (s.duration_minutes || ' minutes')::interval end,
          s.capacity, s.status, s.min_reservation_tier, s.created_by, s.id, v_date
        )
        on conflict (series_id, occurrence_date) where series_id is not null
        do nothing;

        if found then
          v_created := v_created + 1;
        end if;
      end if;
    end loop;
  end loop;

  return v_created;
end;
$$;

-- ── Telling members ─────────────────────────────────────────────────────────
-- The "posts to clients" half. Announcements go out on a lead time before each
-- occurrence rather than when the row is created — a member wants to hear about
-- Friday on Thursday, not about all of next quarter this morning.

create or replace function announce_due_events()
returns int
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  e record;
  v_sent int := 0;
begin
  for e in
    select ev.id, ev.name, ev.starts_at, v.name as venue_name,
           s.announce_audience, s.created_by
      from events ev
      join event_series s on s.id = ev.series_id
      left join venues v on v.id = ev.venue_id
     where ev.announced_at is null
       and ev.status = 'published'
       and s.announce
       and s.status = 'published'
       and ev.starts_at >= now()
       and ev.starts_at <= now() + (s.announce_days_before || ' days')::interval
     order by ev.starts_at
     limit 200
  loop
    insert into member_notifications (audience, kind, title, body, created_by)
    values (
      e.announce_audience,
      'event',
      left(e.name, 140),
      trim(both from
        coalesce(e.venue_name || ' · ', '') ||
        to_char(e.starts_at at time zone 'Africa/Lagos', 'Dy DD Mon, HH12:MIam'))
    , e.created_by);

    update events set announced_at = now() where id = e.id;
    v_sent := v_sent + 1;
  end loop;

  return v_sent;
end;
$$;

revoke execute on function materialise_event_series(int, uuid) from public, anon, authenticated;
revoke execute on function announce_due_events()                from public, anon, authenticated;
grant  execute on function create_event_series(text, event_recurrence, date, time, uuid, int, date, int, int, tier_enum, text, boolean, int, text)
  to authenticated;
revoke execute on function create_event_series(text, event_recurrence, date, time, uuid, int, date, int, int, tier_enum, text, boolean, int, text)
  from public, anon;

-- ── Keeping it running ──────────────────────────────────────────────────────
-- Materialise nightly so the horizon rolls forward; announce hourly so a lead
-- time of 0 days still reaches people during the day it applies to.

-- Guarded as 0005 and 0043 are: without pg_cron the series still materialise
-- and announce when the functions are called, they just are not called on a
-- timer. That is a degraded environment, not a failed migration.
do $guard$
begin
  perform cron.unschedule('materialise-event-series')
   where exists (select 1 from cron.job where jobname = 'materialise-event-series');
  perform cron.schedule('materialise-event-series', '20 3 * * *',
    $job$ select materialise_event_series(60); $job$);

  perform cron.unschedule('announce-due-events')
   where exists (select 1 from cron.job where jobname = 'announce-due-events');
  perform cron.schedule('announce-due-events', '5 * * * *',
    $job$ select announce_due_events(); $job$);
exception when others then
  raise notice 'pg_cron unavailable here (%) — run materialise_event_series() and announce_due_events() externally', sqlerrm;
end;
$guard$;
